### PR TITLE
Fix >= stm-containers-1.0 dependency; upgrade to lts-13.2.

### PR DESCRIPTION
**Pull request by benjaminweb**
stack.yaml might need to be re-considered.

### CODE REVIEW

**Comment by agrafix** [comment]
Thanks! Could you see why the travis build is failing?

**Comment by benjaminweb** [comment]
Done. Any idea how we can simplify version constraints in both `.cabal` and `stack.yaml` files?

**Comment by agrafix** [comment]
Unfortunatley I think we need both :( 

Thanks!

**Comment by sjakobi** [comment]
What needs to be done so this fix can be released?

**Pull request merged**
